# Generated by Django 6.0.1 on 2026-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpcStructCath',
            fields=[
                ('cath_query', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dpc_target', models.CharField(max_length=50)),
                ('q_range', models.CharField(blank=True, max_length=100, null=True)),
                ('t_range', models.CharField(blank=True, max_length=100, null=True)),
                ('qlen', models.IntegerField(blank=True, null=True)),
                ('tlen', models.IntegerField(blank=True, null=True)),
                ('qcov', models.FloatField(blank=True, null=True)),
                ('tcov', models.FloatField(blank=True, null=True)),
                ('alnlen', models.IntegerField(blank=True, null=True)),
                ('qtmscore', models.FloatField(blank=True, null=True)),
                ('ttmscore', models.FloatField(blank=True, null=True)),
                ('alntmscore', models.FloatField(blank=True, null=True)),
                ('lddt', models.FloatField(blank=True, null=True)),
                ('pident', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dpcstruct_cath',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpcStructMcsProperty',
            fields=[
                ('mc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mc_size', models.IntegerField(blank=True, null=True)),
                ('len_aa', models.FloatField(blank=True, null=True)),
                ('len_std', models.FloatField(blank=True, null=True)),
                ('len_ratio', models.FloatField(blank=True, null=True)),
                ('plddt', models.FloatField(blank=True, null=True)),
                ('disorder', models.FloatField(blank=True, null=True)),
                ('tmscore', models.FloatField(blank=True, null=True)),
                ('lddt', models.FloatField(blank=True, null=True)),
                ('pident', models.FloatField(blank=True, null=True)),
                ('pfam_score', models.FloatField(blank=True, null=True)),
                ('pfam_da', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DPCStruct MC Property',
                'verbose_name_plural': 'DPCStruct MC Properties',
                'db_table': 'dpcstruct_mcs_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpcStructMcsSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prot_range', models.CharField(max_length=100)),
                ('prot_seq', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dpcstruct_mcs_sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpcStructScop',
            fields=[
                ('scop_query', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dpc_target', models.CharField(max_length=50)),
                ('q_range', models.CharField(blank=True, max_length=50, null=True)),
                ('t_range', models.CharField(blank=True, max_length=50, null=True)),
                ('qlen', models.IntegerField(blank=True, null=True)),
                ('tlen', models.IntegerField(blank=True, null=True)),
                ('qcov', models.FloatField(blank=True, null=True)),
                ('tcov', models.FloatField(blank=True, null=True)),
                ('alnlen', models.IntegerField(blank=True, null=True)),
                ('qtmscore', models.FloatField(blank=True, null=True)),
                ('ttmscore', models.FloatField(blank=True, null=True)),
                ('alntmscore', models.FloatField(blank=True, null=True)),
                ('lddt', models.FloatField(blank=True, null=True)),
                ('pident', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dpcstruct_scop',
                'managed': False,
            },
        ),
    ]
