# Generated by Django 6.0.1 on 2026-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpcStructMcsProperty',
            fields=[
                ('mc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mc_size', models.IntegerField(blank=True, null=True)),
                ('len_aa', models.FloatField(blank=True, null=True)),
                ('len_std', models.FloatField(blank=True, null=True)),
                ('len_ratio', models.FloatField(blank=True, null=True)),
                ('plddt', models.FloatField(blank=True, null=True)),
                ('disorder', models.FloatField(blank=True, null=True)),
                ('tmscore', models.FloatField(blank=True, null=True)),
                ('lddt', models.FloatField(blank=True, null=True)),
                ('pident', models.FloatField(blank=True, null=True)),
                ('pfam_score', models.FloatField(blank=True, null=True)),
                ('pfam_labels', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dpcstruct_mcs_properties',
                'managed': False,
            },
        ),
    ]
