# Generated by Django 6.0.1 on 2026-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpcstruct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpcStructMcsSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('protein_id', models.CharField(max_length=50)),
                ('prot_range', models.CharField(max_length=100)),
                ('prot_seq', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dpcstruct_mcs_sequences',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dpcstructmcsproperty',
            options={'managed': False, 'verbose_name': 'DPCStruct MC Property', 'verbose_name_plural': 'DPCStruct MC Properties'},
        ),
    ]
