# Generated by Django 6.0.1 on 2026-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpcPfamDomain',
            fields=[
                ('pfam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pfam_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'DPC Pfam Domain',
                'verbose_name_plural': 'DPC Pfam Domains',
                'db_table': 'dpc_pfam_domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpcUniprotProtein',
            fields=[
                ('protein_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('protein_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DPC UniProt Protein',
                'verbose_name_plural': 'DPC UniProt Proteins',
                'db_table': 'dpc_uniprot_proteins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpcUniref50Pfam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfam_ranges', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dpc_uniref50_pfam',
                'managed': False,
            },
        ),
    ]
