# Generated by Django 6.0.1 on 2026-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpcfamAlphaFoldRep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alphafold_prot', models.TextField()),
                ('seq_range', models.CharField(max_length=100)),
                ('hmm_coverage', models.FloatField()),
                ('avg_plddt', models.FloatField()),
            ],
            options={
                'verbose_name': 'DPCFam AlphaFold Representative',
                'verbose_name_plural': 'DPCFam AlphaFold Representatives',
                'db_table': 'dpcfam_alphafold_reps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpcfamMcsProperty',
            fields=[
                ('mcid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('size_uniref50', models.IntegerField(blank=True, null=True)),
                ('avg_len', models.FloatField(blank=True, null=True)),
                ('std_avg_len', models.FloatField(blank=True, null=True)),
                ('lc_percent', models.FloatField(blank=True, null=True)),
                ('cc_percent', models.FloatField(blank=True, null=True)),
                ('dis_percent', models.FloatField(blank=True, null=True)),
                ('tm', models.FloatField(blank=True, null=True)),
                ('pfam_da', models.TextField(blank=True, null=True)),
                ('da_percent', models.FloatField(blank=True, null=True)),
                ('avg_ov_percent', models.FloatField(blank=True, null=True)),
                ('overlap_label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'DPCFam MC Property',
                'verbose_name_plural': 'DPCFam MC Properties',
                'db_table': 'dpcfam_mcs_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpcfamMcsSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq_range', models.CharField(max_length=100)),
                ('seq_length', models.IntegerField()),
                ('aa_seq', models.TextField()),
            ],
            options={
                'db_table': 'dpcfam_mcs_sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniRef50Pfam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfam_ids', models.CharField(max_length=50)),
                ('pfam_ranges', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'uniref50_pfam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniRef50Protein',
            fields=[
                ('uniref50_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uniprotkb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uniprotkb_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uniref50_proteins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlphaFold',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dpcfam.dpcfamalphafoldrep',),
        ),
        migrations.CreateModel(
            name='MCSProperty',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dpcfam.dpcfammcsproperty',),
        ),
        migrations.CreateModel(
            name='MCSSequence',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dpcfam.dpcfammcssequence',),
        ),
    ]
