# Generated by Django 6.0.1 on 2026-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpcfamMetacluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('size_uniref50', models.IntegerField()),
                ('avg_len', models.FloatField()),
                ('lc_percent', models.FloatField()),
                ('cc_percent', models.FloatField()),
                ('dis_percent', models.FloatField()),
                ('tm', models.FloatField()),
                ('pfam_da', models.CharField(max_length=50)),
                ('da_percent', models.FloatField(blank=True, null=True)),
                ('size_pfam', models.IntegerField(blank=True, null=True)),
                ('overlap_type', models.CharField(max_length=20)),
            ],
        ),
    ]
