# Generated by Django 6.0.1 on 2026-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaFold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alphafold_prot', models.TextField()),
                ('seq_range', models.CharField(max_length=100)),
                ('hmm_coverage', models.FloatField()),
                ('avg_plddt', models.FloatField()),
            ],
            options={
                'db_table': 'alphafold_reps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCSProperty',
            fields=[
                ('mcid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('size_uniref50', models.IntegerField(blank=True, null=True)),
                ('avg_len', models.FloatField(blank=True, null=True)),
                ('std_avg_len', models.FloatField(blank=True, null=True)),
                ('lc_percent', models.FloatField(blank=True, null=True)),
                ('cc_percent', models.FloatField(blank=True, null=True)),
                ('dis_percent', models.FloatField(blank=True, null=True)),
                ('tm', models.FloatField(blank=True, null=True)),
                ('pfam_da', models.TextField(blank=True, null=True)),
                ('da_percent', models.FloatField(blank=True, null=True)),
                ('size_pfam', models.IntegerField(blank=True, null=True)),
                ('avg_ov_percent', models.FloatField(blank=True, null=True)),
                ('overlap_label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mcs_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCSSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq_range', models.CharField(max_length=100)),
                ('seq_length', models.IntegerField()),
                ('aa_seq', models.TextField()),
            ],
            options={
                'db_table': 'mcs_sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniRef50Pfam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pfam_ids', models.CharField(max_length=50)),
                ('pfam_ranges', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'uniref50_pfam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniRef50Protein',
            fields=[
                ('uniref50_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uniprotkb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uniprotkb_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uniref50_proteins',
                'managed': False,
            },
        ),
    ]
