# Generated by Django 6.0.1 on 2026-02-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpcfam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCSProperty',
            fields=[
                ('mcid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('size_uniref50', models.IntegerField(blank=True, null=True)),
                ('avg_len', models.FloatField(blank=True, null=True)),
                ('lc_percent', models.FloatField(blank=True, null=True)),
                ('cc_percent', models.FloatField(blank=True, null=True)),
                ('dis_percent', models.FloatField(blank=True, null=True)),
                ('tm', models.FloatField(blank=True, null=True)),
                ('size_pfam', models.IntegerField(blank=True, null=True)),
                ('pfam_da', models.CharField(blank=True, max_length=200, null=True)),
                ('da_percent', models.FloatField(blank=True, null=True)),
                ('overlap_label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mcs_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCSSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mcid', models.CharField(max_length=100)),
                ('protein', models.CharField(max_length=255)),
                ('range_str', models.CharField(db_column='range_str', max_length=100)),
                ('aa_length', models.IntegerField(db_column='aa_length')),
                ('amino_acids', models.TextField()),
            ],
            options={
                'db_table': 'mcs_sequences',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DpcfamMetacluster',
        ),
    ]
